name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats image
        uses: lowlighter/metrics@latest
        with:
          filename: stats/github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: KhurramRashid6893
          template: classic
          base: header, activity, repositories, languages
          config_timezone: Asia/Kolkata
